config/routes.rb
  Kupid::Application.routes.draw do

    constraints :subdomain => '' do
      match '(*any)' => redirect { |p, req| req.url.sub('//', '//www.') }
    end

  resources :matches
    match 'about', :to => 'matches#about', :as => :about_page

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

   root :to => 'matches#index'

end

app/models/match.rb
class Match < ActiveRecord::Base

  belongs_to :user
  
  attr_accessible :female, :male, :user_id, :result
  
  serialize :female
  serialize :male

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  # Omniauth	
  attr_accessible :provider, :uid, :name, :oauth_token, :oauth_expires_at

  has_many :matches

def self.from_omniauth(auth)
  where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
    user.provider = auth.provider
    user.uid = auth.uid
    user.oauth_token = auth.credentials.token
    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
    user.save!
  end
end


def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
  user = User.where(:provider => auth.provider, :uid => auth.uid).first
  unless user
    user = User.create(  name:auth.extra.raw_info.name,
                         provider:auth.provider,
                         uid:auth.uid,
                         email:auth.info.email,
                         oauth_token:auth.credentials.token,
                         oauth_expires_at:Time.at(auth.credentials.expires_at),
                         password:Devise.friendly_token[0,20]
                         )
  end
  user
end


def self.add_action(user_id, match_url)
  user = User.find(user_id)
  user.facebook.put_connections("me", "dudesetmeup:set_up", match: match_url) 
end



  def conditions(male, female)
    boy = male
    girl = female
    if (!boy["birthday_date"].nil? && !girl["birthday_date"].nil?) && (boy["birthday_date"].size == 10 && girl["birthday_date"].size == 10)
      boy_age = Time.now.year - boy["birthday_date"][boy["birthday_date"].size, boy["birthday_date"].size-4].to_i
      girl_age = Time.now.year - girl["birthday_date"][girl["birthday_date"].size, girl["birthday_date"].size-4].to_i
    end

    if !boy_age.nil? && !girl_age.nil? 
      if ((boy_age/2)+7) <= girl_age
        false
      end

     elsif boy["last_name"] == girl["last_name"] # DEAL BREAKER!
       false

    elsif (boy["relationship_status"] == "In a relationship") || (boy["relationship_status"]  == "Married") || (boy["relationship_status"] == "Engaged") || (girl["relationship_status"] == "In a relationship") || (girl["relationship_status"] == "Engaged") || (girl["relationship_status"] == "Married")
      false # We are not family wreckers

    else
      true
    end
  end

  def raw(male, female)
    if !conditions(male, female)
      raw(self.male_list.sample, self.female_list.sample)
    else        
      perfect_match = []
      perfect_match << female
      perfect_match << male
    end
  end

  def facebook 
    @facebook ||= Koala::Facebook::API.new(oauth_token)
  end

  def female_list
    female_list = []
    female_list = facebook.fql_query("select name, uid, last_name, relationship_status, birthday_date, pic_big from user where sex='female' AND (relationship_status<>'In a relationship' OR 'Married') AND uid in (select uid2 from friend where uid1=me())").to_a
  end

  def male_list
    male_list = []
    male_list = facebook.fql_query("select name, uid, last_name, relationship_status, birthday_date, pic_big from user where sex='male' AND (relationship_status<>'In a relationship' OR 'Married') AND uid in (select uid2 from friend where uid1=me())").to_a
  end
  
end

app/controllers/application_controller.rb
# encoding: utf-8
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/matches_controller.rb
# encoding: utf-8
include ApplicationHelper

class MatchesController < ApplicationController
	before_filter :authenticate, :except => [:show, :about, :index]
	def index
		if user_signed_in?		
			perfect_match = current_user.raw(current_user.male_list.sample, current_user.female_list.sample)
			flash[:female] = perfect_match[0]
			@female = flash[:female]
			@male = perfect_match[1]
			flash[:male] = perfect_match[1]
			@match = Match.new
		end
	end


	def create
		@match = Match.new
		@match.female = flash[:female]
		@match.male = flash[:male]

		if params[:yes]
			@match.result = true
		else
			@match.result = false
		end
		@match.user = current_user
		
		respond_to do |format|
			if @match.save
				if current_user && params[:yes]
	      			User.delay.add_action(current_user.id, match_url(@match))
		      		# current_user.facebook.put_wall_post("I just set up " + @match.female["name"] + " & " + @match.male["name"] + " on \"dude set me up\"", {:name => @match.female["name"] + " & " + @match.male["name"], :link => match_url(@match) })
		      		# current_user.facebook.put_object("yochay", "dudesetmeup")
  					format.html { redirect_to matches_path, notice: 'השידך בין ' + "<a href=" + match_url(@match) + ">" + @match.female["name"] + ' לבין ' + @match.male["name"] + '</a> בוצע בהצלחה! ' + like_link(match_url(@match)) }
  				else
  					format.html { redirect_to matches_path }
		        end
		  else
		  	  format.html { redirect_to matches_path }
			end

		  end

	end

	def show
		@match = Match.find(params[:id])
		redirect_to '/' if @match.result == false
	end

	def about

	end

	def authenticate
		if !user_signed_in?
			redirect_to matches_path
		end
	end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

def passthru
  render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
  # Or alternatively,
  # raise ActionController::RoutingError.new('Not Found')
end

end

app/helpers/application_helper.rb
# encoding: utf-8

module ApplicationHelper
	def randomize_index_phrase
		phrases = []
		phrases << "אז מה אם אתה <span style=\"color: #b95959;\">\"In a Relationship\"</span>, זה לא אומר שאתה לא יכול לדאוג לחברים'שך"
		phrases << "עזוב אחי.. תפרגן לו.. הוא <span style=\"color: #b95959;\">לא במצב של לסנן..</span>"
		phrases << "מה נשאר לחברים שלך לעשות? <span style=\"color: #b95959;\">רק להתכופף ולקטוף</span>"
		phrases << "הוא סבבה והכל אבל.. <span style=\"color: #b95959;\">בלי אבל!</span> סדרי לי אותו!"
		phrases << "תגידי.. אממ.. אולי.. אממ.. נו.. אולי.. <span style=\"color: #b95959;\">אולי תסדרי לי כבר מישהו?!</span>"
		return phrases.sample
	end

	def randomize_happy_phrase
		phrases = []
		phrases << "איזה יופי, שידוך משמים"
		phrases << "dear beloved we are gathered here today"
		phrases << "שמלה כבר יש?"
		phrases << "דיג'יי או להקה?"
		return phrases.sample
	end

	def like_link(match_url)
		"<div class=\"fb-like\" style=\"float: left;\" data-href=\"" + match_url + "\" data-send=\"true\" data-layout=\"button_count\" data-width=\"450\" data-show-faces=\"false\"></div>
             </div>"
	end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/match_helper.rb
module MatchHelper

	# def add_action_to_facebook
		
	# end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html dir=rtl>
<head>
  <title>dude set me up - social pick app</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
  <link rel="shortcut icon" href="/assets/favicon.ico" type="image/x-icon" />
</head>
<body>
    <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=354930974593675";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>

    <div id="wrapper">
        <div id="topbar">
            <a href="/"><img src="/assets/logo.gif" alt="" height="260" border="" ></a>
        </div>
        <div id="content">
          <%= yield %>
        </div>

    </div>

        <div style="clear:both;"></div>
        <div id="footer">
          <ul>
            <li><%= link_to "ראשי", matches_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to "לוג אאוט (" + current_user.name + ")", destroy_user_session_path, :method => :delete %></li>
            <% end %>
            <li><%= link_to "אודות וכו'", about_page_path %></li>
          </ul>
        </div>
        <br><br>
</body>
</html>

app/views/matches/about.html.erb
<p class="textright">
	<span class="title_of_p">אודות</span>
סיר ז'אן פול דה-לה-ריליישן אמר פעם, "לכל סיר יש מכסה". <br />קל להתנחם במשפטים קלישאתיים כמו זה (כי הרי ברור שהם נכונים), בעודך מהנהנת בחביבות לעוד דייט כושל, שברור לך שייגמר במרתון של "האנטומיה של גריי", בבית. לבד. <br />
גם קל לחלוק גלידה של B&J עם איזה חברה שמתייפחת על זה שעוד פעם זרקו אותה, והאביר על הסוס הלבן נראה רחוק מתמיד.
ונורא פשוט לשבת על איזה כוס בירה ולהנהנן כשחבר שלך מתאר לך את הבחורה החדשה שאיתה הוא הולך לצאת, והרי רק לפי הסיפור, ברור לך שאין מצב שסטודנט מבצלאל שמבלה את הסופ"שים בחומוס בשייח' ג'ראח, יחזיק עם חצאית מתנפנפת מהרי השומרון, יותר משבוע.. למרות הכוונות הטובות של שניהם.<br /><br />

אז למה שלא תעשה מעשה?<br />
מי יכול לעזור לחברים'שך יותר טוב ממך? ימי רביעי בגלינה? "אין שני ליום שני" באומן? <br />הגיסה שלא מפסיקה לשדך? השכנה של החבר שמתפללת על זיווג טוב בשבילו?  לא!! אתה!<br />
חברים, הם בעלי אחוזי ההצלחה הגבוהים ביותר במציאת שידוכים. 
<br /><br />
בעזרת האלגוריתם של <a href="http://www.dudesetmeup.com/">dude set me up</a>, תוכל למצוא זיווגים הולמים לחברים הטובים שלך! <br />
אספנו בשבילך מהפייסבוק את כל החברים, הרווקים והרווקות והצלבנו אותם אחד עם השני.
ההצלבה נעשית תוך התחשבות בשלום בית- הורדנו חברים אשר נמצאים במערכות יחסים. שימוש גם בחוק השבע (גיל הגבר/7+2)- כדי להגביר אחוזי התאמה (ולמנוע שימוש לרעה באפליקציה).<br /> וכן, מניעת שידוכים בין קרובי משפחה (יש דברים שלא צריך להסביר).<br />
לך, רק נשאר ללחוץ על הכפתור, ולומר אם כן או לא.  <br /><br />

בקיצור, התחבר למערכת, שדך את החברים, ואל תשכח לשלוח את הטוקסידו לניקוי יבש :)
</p>

<p class="textleft">
	<span class="title_of_p">צור קשר ודאחקות</span>
המיזם עלה ע"י שלושה חבר'ה יוצאי סיירות מובחרת בצה"ל אשר שמו לעצמם כמטרה להנחיל את ערכי הסיירת בחברים פחות מוצלחים. שלושת החברים, ילידי קיבוץ בצפון, סתם נו יאללה.. <br /><br />
האפליקציה פותחה במסגרת "יומיים פיתוח" שהתקיימו בהשראת ה- <a href="http://www.fbworldhack.com/" target="_blank"> Facebook World Hack</a> (אירועי פיתוח חובקי עולם של פייסבוק).<br /><br />
אז אמנם לא היו מאות משתתפים (אחד), והמשאבים היו מעטים (בלי מהנדסים מפייסבוק) והכיבוד היה דל (ויטמיצ'יק בגיל 22 זה נוראי?) אבל מה שכן, יצאה אחלה אפליקציה. ואפילו מאוד. <br /> <br />

בסיוע של קהילת <a href="http://www.github.com/" target="_blank">הקוד הפתוח</a>, אנשי <a href="http://www.freenode.net/" target="_blank">הקודקדים החופשיים</a> הצלחתי להרים האפליקציה, שנכתבה ב-Ruby on Rails, תוך יומיים של עבודה ועם "הרבה אהבה".  <br /> <br />

מענות, הארות, הערות ובאגים - yochze @ gmail . com (צמצמו רווחים).

</p>
<% content_for :head do %>
    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-34929801-1']);
      _gaq.push(['_setDomainName', 'dudesetmeup.com']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

</script>
<% end %>

app/views/matches/index.html.erb
        <% if notice %>
            <div id="notice">
                <img src="/assets/hearticon.png" border="0" alt="" text="" />
                 <%= notice.html_safe %>
        <% end %>
    <h1>
        <%= randomize_index_phrase.html_safe %>
    </h1> 
<% if !user_signed_in? %>
<br> <br> <br>
            <div id="facebook-mainpage">
                <a href="/users/auth/facebook"><img src="/assets/facebook.gif" alt="" border=""></a><p>
                    התחברו עכשיו
                    <br>
                        והתחילו לשחק אותה שדכנים<Br>
                        בין החברים שלכם
                </p>
            </div> 
<% else %>
    <div class="couple_wrapper">
        <div class="match_wrapper">
            <p class="caption">
          <%= image_tag(@female["pic_big"], :size => '200x220', :class => 'perfect_match_image') %>
                <span><%= @female["name"] %></span>
            </p>
        </div> 

        <div class="match_wrapper">
            <p class="caption">
                <%= image_tag(@male["pic_big"], :size => '200x220', :class => 'perfect_match_image', :id => 'default') %>
                <span><%= @male["name"] %></span>
            </p>
        </div>
<br><br>
        <br /> <br />
        <%= form_for(@match) do |f| %>
            <%= f.submit "דווקא זורם", :name => "yes", :class => "btn-yes" %>
            <%= f.submit "וואלה לא מתאים", :name => "no", :class => "btn-no" %> 
        <% end %>
    </div>  
<% end %>


<% content_for :head do %>
    <meta property="og:title" content="Dude! Set me up!" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="http://www.dudesetmeup.com" />
    <meta property="og:site_name" content="dudesetmeup" />
    <meta property="og:image" content="http://www.dudesetmeup.com/assets/logo.gif" />
    <meta property="og:description" content="Social pick app that help you match between your friends." />

    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-34929801-1']);
      _gaq.push(['_setDomainName', 'dudesetmeup.com']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

</script>
<% end %>

app/views/matches/show.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=354930974593675";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<h1>
	<%= randomize_happy_phrase.html_safe %>
</h1> 
<div class="heartbg">
    <div class="couple_wrapper">
        <div class="match_wrapper">
            <p class="caption">
          <%= image_tag(@match.female["pic_big"], :size => '200x220', :class => 'perfect_match_image') %>
                <span><%= @match.female["name"] %></span>
            </p>
        </div> 

        <div class="match_wrapper">
            <p class="caption">
                <%= image_tag(@match.male["pic_big"], :size => '200x220', :class => 'perfect_match_image', :id => 'default') %>
                <span><%= @match.male["name"] %></span>
            </p>
        </div>
        <div class="matchedby">
			<span class="matchedby_name"><%= @match.user.name %></span>
        </div>
   </div>
   <div style="margin-left: auto; margin-right: auto; text-direction: center;" >
     <div class="fb-like" style="margin-left: auto; margin-right: auto;" data-href="<%= match_url(@match) %>" data-send="true" data-layout="button_count" data-width="450" data-show-faces="false"></div>
   </div>
  </div>
<br> <br>

<% content_for :head do %>

  <%= tag :meta, property: "fb:app_id", content: "354930974593675" %>
  <%= tag :meta, property: "og:site_name", content: "dude set me up" %>
  <%= tag :meta, property: "og:type", content: "dudesetmeup:match" %>
  <%= tag :meta, property: "og:title", content: @match.male["name"] + ' & ' + @match.female["name"] %>
  <%= tag :meta, property: "og:url", content: match_url(@match) %>


<% end %>

<% content_for :head do %>
    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-34929801-1']);
      _gaq.push(['_setDomainName', 'dudesetmeup.com']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

</script>
<% end %>